# vim: ft=dosini
#
# aerc Abysal styleset
# set styleset-name=abysal-xxx.ini in 'aerc.conf' to load the style
#

*.default=true
*.normal=true

border.fg=#525252
border.bg=#1c1c1c

title.fg=#161616
title.bg=#6b92e3
title.bold=true

header.fg=#d47779
#header.bg=#1c1c1c
header.bold=true

tab.fg=#525252
tab.bg=#262626
tab.selected.fg=#161616
tab.selected.bg=#6b92e3

statusline_default.fg=#d4d4d4
statusline_default.bg=#262626
statusline_error.fg=#c44040
statusline_success.fg=#52c9b0

*error.bold=true
*error.fg=#c44040
*warning.fg=#d1b171
*success.fg=#52c9b0

dirlist_*.bg=#1c1c1c
dirlist_*.fg=#d4d4d4
dirlist_*.selected.bg=#232b4e
dirlist_*.selected.fg=#d4d4d4

msglist_*.bg=#1c1c1c
msglist_*.fg=#d4d4d4
msglist_*.selected.bg=#232b4e
#msglist_*.selected.fg=#d4d4d4
msglist_unread.bold=true
msglist_unread.fg=#6b92e3
msglist_marked.fg=#e28e5a
msglist_thread_folded.italic=true
msglist_thread_folded.underline=true
msglist_gutter.bg=#333333
msglist_pill.bg=#525252
msglist_pill.reverse=false

part_*.fg=#d4d4d4
part_*.bg=#262626
part_*.selected.fg=#d4d4d4
part_*.selected.bg=#525252

completion_default.bg=#262626
completion_default.fg=#d4d4d4
completion_default.selected.bg=#525252
completion_default.selected.fg=#d4d4d4
completion_gutter.bg=#333333
completion_pill.bg=#525252
completion_pill.reverse=false

spinner.bg=#1c1c1c
spinner.fg=#d4d4d4

selector_focused.bold=false
selector_focused.bg=#232b4e
selector_focused.fg=#d4d4d4
selector_chooser.bold=false
selector_chooser.bg=#232b4e
selector_chooser.fg=#d4d4d4
default.selected.bold=false
default.selected.fg=#d4d4d4
default.selected.bg=#232b4e

[viewer]
url.underline=true
url.fg=#8c8c8c
header.fg=#b87bce
signature.fg=#b87bce
diff_add.fg=#253f3b
diff_del.fg=#462525
diff_meta.bold=true
diff_chunk.dim=true
quote_1.fg=#d1b171
quote_2.fg=#52c9b0
quote_3.fg=#52c9b0
quote_3.dim=true
quote_4.fg=#6b92e3
quote_4.dim=true
quote_x.fg=#737373
quote_x.dim=true

