# vim: ft=dosini
#
# aerc Abysal styleset
# set styleset-name=abysal-xxx.ini in 'aerc.conf' to load the style
#

*.default=true
*.normal=true

border.fg=#8c8c8c
border.bg=#dcdcdc

title.fg=#b0b0b0
title.bg=#365ca8
title.bold=true

header.fg=#a8474a
#header.bg=#dcdcdc
header.bold=true

tab.fg=#8c8c8c
tab.bg=#cfcfcf
tab.selected.fg=#b0b0b0
tab.selected.bg=#365ca8

statusline_default.fg=#2f2f2f
statusline_default.bg=#cfcfcf
statusline_error.fg=#8c2d30
statusline_success.fg=#2c9279

*error.bold=true
*error.fg=#8c2d30
*warning.fg=#7a6020
*success.fg=#2c9279

dirlist_*.bg=#dcdcdc
dirlist_*.fg=#2f2f2f
dirlist_*.selected.bg=#a2b0d1
dirlist_*.selected.fg=#2f2f2f

msglist_*.bg=#dcdcdc
msglist_*.fg=#2f2f2f
msglist_*.selected.bg=#a2b0d1
#msglist_*.selected.fg=#2f2f2f
msglist_unread.bold=true
msglist_unread.fg=#365ca8
msglist_marked.fg=#a04e1e
msglist_thread_folded.italic=true
msglist_thread_folded.underline=true
msglist_gutter.bg=#c4c4c4
msglist_pill.bg=#8c8c8c
msglist_pill.reverse=false

part_*.fg=#2f2f2f
part_*.bg=#cfcfcf
part_*.selected.fg=#2f2f2f
part_*.selected.bg=#8c8c8c

completion_default.bg=#cfcfcf
completion_default.fg=#2f2f2f
completion_default.selected.bg=#8c8c8c
completion_default.selected.fg=#2f2f2f
completion_gutter.bg=#c4c4c4
completion_pill.bg=#8c8c8c
completion_pill.reverse=false

spinner.bg=#dcdcdc
spinner.fg=#2f2f2f

selector_focused.bold=false
selector_focused.bg=#a2b0d1
selector_focused.fg=#2f2f2f
selector_chooser.bold=false
selector_chooser.bg=#a2b0d1
selector_chooser.fg=#2f2f2f
default.selected.bold=false
default.selected.fg=#2f2f2f
default.selected.bg=#a2b0d1

[viewer]
url.underline=true
url.fg=#555555
header.fg=#824699
signature.fg=#824699
diff_add.fg=#aec3be
diff_del.fg=#c8b0b1
diff_meta.bold=true
diff_chunk.dim=true
quote_1.fg=#7a6020
quote_2.fg=#2c9279
quote_3.fg=#2c9279
quote_3.dim=true
quote_4.fg=#365ca8
quote_4.dim=true
quote_x.fg=#666666
quote_x.dim=true

