[[themes]]
name = "Abysal Obsidian"
[themes.palette]
background = "#262626"
foreground = "#8c8c8c"
black = "#2e2e2e"
red = "#d47779"
green = "#52c9b0"
yellow = "#d1b171"
blue = "#6b92e3"
magenta = "#b87bce"
cyan = "#52c9b0"
white = "#8c8c8c"
bright_black = "#1c1c1c"
bright_red = "#c44040"
bright_green = "#52c9b0"
bright_yellow = "#e28e5a"
bright_blue = "#89aae8"
bright_magenta = "#d45daa"
bright_cyan = "#8ca8e0"
bright_white = "#d4d4d4"
