[[themes]]
name = "Abysal Marble"
[themes.palette]
background = "#cfcfcf"
foreground = "#555555"
black = "#bcbcbc"
red = "#a8474a"
green = "#2c9279"
yellow = "#7a6020"
blue = "#365ca8"
magenta = "#824699"
cyan = "#2c9279"
white = "#555555"
bright_black = "#dcdcdc"
bright_red = "#8c2d30"
bright_green = "#2c9279"
bright_yellow = "#a04e1e"
bright_blue = "#2a4d94"
bright_magenta = "#a83280"
bright_cyan = "#5878b8"
bright_white = "#2f2f2f"
