local Util = require("abysal.util")

local M = {}

---@type abysal.HighlightsFn
function M.get(c)
  -- stylua: ignore
  return {
    ["@lsp.type.boolean"]                      = "@boolean",
    ["@lsp.type.builtinType"]                  = "@type.builtin",
    ["@lsp.type.class"]                        = "@type",
    ["@lsp.type.comment"]                      = "@comment",
    ["@lsp.type.decorator"]                    = "@attribute",
    ["@lsp.type.deriveHelper"]                 = "@attribute",
    ["@lsp.type.enum"]                         = "@type",
    ["@lsp.type.enumMember"]                   = "@constant",
    ["@lsp.type.event"]                        = "@function",
    ["@lsp.type.escapeSequence"]               = "@string.escape",
    ["@lsp.type.formatSpecifier"]              = "@markup.list",
    ["@lsp.type.function"]                     = "@function",
    ["@lsp.type.generic"]                      = "@variable",
    ["@lsp.type.interface"]                    = "@type",
    ["@lsp.type.keyword"]                      = "@keyword",
    ["@lsp.type.lifetime"]                     = "@keyword.storage",
    ["@lsp.type.method"]                       = "@method",
    ["@lsp.type.modifier"]                     = "@keyword.storage",
    ["@lsp.type.namespace"]                    = "@module",
    ["@lsp.type.namespace.python"]             = "@function",
    ["@lsp.type.number"]                       = "@number",
    ["@lsp.type.operator"]                     = "@operator",
    ["@lsp.type.parameter"]                    = "@variable.parameter",
    ["@lsp.type.property"]                     = "@property",
    ["@lsp.type.regexp"]                       = "@string.regexp",
    ["@lsp.type.selfKeyword"]                  = "@variable.builtin",
    ["@lsp.type.selfTypeKeyword"]              = "@variable.builtin",
    ["@lsp.type.string"]                       = "@string",
    ["@lsp.type.struct"]                       = "@type",
    ["@lsp.type.type"]                         = "@type",
    ["@lsp.type.typeAlias"]                    = "@type.definition",
    ["@lsp.type.typeParameter"]                = "@type",
    ["@lsp.type.unresolvedReference"]          = { undercurl = true, sp = c.error },
    ["@lsp.type.variable"]                     = {}, -- use treesitter styles for regular variables
    ["@lsp.typemod.class.defaultLibrary"]      = "@type.builtin",
    ["@lsp.typemod.enum.defaultLibrary"]       = "@type.builtin",
    ["@lsp.typemod.enumMember.defaultLibrary"] = "@constant.builtin",
    ["@lsp.typemod.function.defaultLibrary"]   = "@function.builtin",
    ["@lsp.typemod.keyword.async"]             = "@keyword.coroutine",
    ["@lsp.typemod.keyword.injected"]          = "@keyword",
    ["@lsp.typemod.macro.defaultLibrary"]      = "@function.builtin",
    ["@lsp.typemod.method.defaultLibrary"]     = "@function.builtin",
    ["@lsp.typemod.operator.injected"]         = "@operator",
    ["@lsp.typemod.string.injected"]           = "@string",
    ["@lsp.typemod.struct.defaultLibrary"]     = "@type.builtin",
    ["@lsp.typemod.type.defaultLibrary"]       = "@type.builtin",
    ["@lsp.typemod.typeAlias.defaultLibrary"]  = "@type.builtin",
    ["@lsp.typemod.variable.callable"]         = "@function",
    ["@lsp.typemod.variable.defaultLibrary"]   = "@variable.builtin",
    ["@lsp.typemod.variable.injected"]         = "@variable",
    ["@lsp.typemod.variable.static"]           = "@constant",

    -- Language-scoped overrides (mirror treesitter.lua per-language captures)
    ["@lsp.type.function.python"]              = "@function.python",
    ["@lsp.type.method.python"]                = "@function.method.python",
    ["@lsp.type.type.python"]                  = "@type.python",
    ["@lsp.type.class.python"]                 = "@type.python",
    ["@lsp.type.enum.python"]                  = "@type.python",
    ["@lsp.type.interface.python"]             = "@type.python",
    ["@lsp.type.struct.python"]                = "@type.python",
    ["@lsp.type.typeParameter.python"]         = "@type.python",
    ["@lsp.type.selfKeyword.python"]           = "@variable.builtin.python",

    ["@lsp.type.type.typescript"]              = "@type.typescript",
    ["@lsp.type.class.typescript"]             = "@type.typescript",
    ["@lsp.type.enum.typescript"]              = "@type.typescript",
    ["@lsp.type.interface.typescript"]         = "@type.typescript",
    ["@lsp.type.struct.typescript"]            = "@type.typescript",
    ["@lsp.type.typeParameter.typescript"]     = "@type.typescript",
    ["@lsp.type.builtinType.typescript"]       = "@type.builtin.typescript",

    ["@lsp.type.type.java"]                    = "@type.java",
    ["@lsp.type.class.java"]                   = "@type.java",
    ["@lsp.type.enum.java"]                    = "@type.java",
    ["@lsp.type.interface.java"]               = "@type.java",
    ["@lsp.type.struct.java"]                  = "@type.java",
    ["@lsp.type.typeParameter.java"]           = "@type.java",
    ["@lsp.type.builtinType.java"]             = "@type.builtin.java",
    ["@lsp.type.modifier.java"]                = "@keyword.modifier.java",
    ["@lsp.type.enumMember.java"]              = "@constant.java",

    ["@lsp.type.type.sql"]                     = "@type.sql",
    ["@lsp.type.class.sql"]                    = "@type.sql",
    ["@lsp.type.enum.sql"]                     = "@type.sql",
    ["@lsp.type.interface.sql"]                = "@type.sql",
    ["@lsp.type.struct.sql"]                   = "@type.sql",
    ["@lsp.type.typeParameter.sql"]            = "@type.sql",
    ["@lsp.type.function.sql"]                 = "@function.sql",
    ["@lsp.type.number.sql"]                   = "@number.sql",
    ["@lsp.type.operator.sql"]                 = "@operator.sql",
    ["@lsp.type.string.sql"]                   = "@string.sql",

    ["@lsp.type.type.hcl"]                     = "@type.hcl",
    ["@lsp.type.class.hcl"]                    = "@type.hcl",
    ["@lsp.type.enum.hcl"]                      = "@type.hcl",
    ["@lsp.type.interface.hcl"]                = "@type.hcl",
    ["@lsp.type.struct.hcl"]                   = "@type.hcl",
    ["@lsp.type.typeParameter.hcl"]            = "@type.hcl",
    ["@lsp.type.number.hcl"]                   = "@number.hcl",
    ["@lsp.type.string.hcl"]                   = "@string.hcl",

    ["@lsp.type.type.toml"]                    = "@type.toml",
    ["@lsp.type.class.toml"]                   = "@type.toml",
    ["@lsp.type.enum.toml"]                    = "@type.toml",
    ["@lsp.type.interface.toml"]               = "@type.toml",
    ["@lsp.type.struct.toml"]                  = "@type.toml",
    ["@lsp.type.typeParameter.toml"]           = "@type.toml",
    ["@lsp.type.number.toml"]                  = "@number.toml",
    ["@lsp.type.property.toml"]                = "@property.toml",
    ["@lsp.type.string.toml"]                  = "@string.toml",

    ["@lsp.type.property.yaml"]                = "@property.yaml",
    ["@lsp.type.number.yaml"]                  = "@number.yaml",
    ["@lsp.type.string.yaml"]                  = "@string.yaml",
    ["@lsp.type.comment.yaml"]                 = "@comment.yaml",

    ["@lsp.type.property.json"]                = "@property.json",
    ["@lsp.type.number.json"]                  = "@number.json",
    ["@lsp.type.string.json"]                  = "@string.json",

    ["@lsp.type.function.bash"]                = "@function.bash",
    ["@lsp.type.keyword.bash"]                 = "@keyword.bash",
    ["@lsp.type.variable.bash"]                = "@variable.bash",
    ["@lsp.type.string.bash"]                  = "@string.bash",
    ["@lsp.type.number.bash"]                  = "@number.bash",
    ["@lsp.type.operator.bash"]                = "@operator.bash",

    ["@lsp.type.string.html"]                  = "@string.html",

    ["@lsp.type.property.css"]                 = "@property.css",
    ["@lsp.type.number.css"]                   = "@number.css",
    ["@lsp.type.string.css"]                   = "@string.css",
    ["@lsp.type.function.css"]                 = "@function.css",

    ["@lsp.type.property.scss"]                = "@property.scss",
    ["@lsp.type.function.scss"]                = "@function.scss",
    ["@lsp.type.variable.scss"]                = "@variable.scss",

    ["@lsp.type.function.dockerfile"]          = "@function.dockerfile",
    ["@lsp.type.string.dockerfile"]            = "@string.dockerfile",
    ["@lsp.type.number.dockerfile"]            = "@number.dockerfile",

  }
end

return M
