# vim:ft=kitty

## name: Abysal Obsidian
## license: MIT
## author: Folke Lemaitre
## upstream: ${_upstream_url}


background #1c1c1c
foreground #d4d4d4
selection_background #232b4e
selection_foreground #d4d4d4
url_color #52c9b0
cursor #d4d4d4
cursor_text_color #1c1c1c

# Tabs
active_tab_background #6b92e3
active_tab_foreground #262626
inactive_tab_background #333333
inactive_tab_foreground #737373
#tab_bar_background #161616

# Windows
active_border_color #6b92e3
inactive_border_color #333333

# normal
color0 #161616
color1 #d47779
color2 #52c9b0
color3 #d1b171
color4 #6b92e3
color5 #b87bce
color6 #52c9b0
color7 #8c8c8c

# bright
color8  #2e2e2e
color9  #e98183
color10 #00dcbc
color11 #e8bd56
color12 #739ff9
color13 #cd82e7
color14 #00dcbc
color15 #d4d4d4

# extended colors
color16 #e28e5a
color17 #c44040
