name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim-version: [stable, nightly]
    steps:
      - uses: actions/checkout@v4
      - name: Install hererocks build dependencies
        run: sudo apt-get update && sudo apt-get install -y libreadline-dev
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim-version }}
      - run: ./scripts/test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install selene
        run: |
          asset_url=$(curl -sLf https://api.github.com/repos/Kampfkarren/selene/releases/latest \
            | jq -r '[.assets[] | select(.name | test("^selene-[0-9].*linux"; "i"))][0].browser_download_url')
          curl -sLf "$asset_url" -o selene.zip
          unzip selene.zip selene
          chmod +x selene
          sudo mv selene /usr/local/bin/selene
      - run: selene lua/
