# -----------------------------------------------------------------------------
# Theme: Abysal Marble
# Upstream: ${_upstream_url}
# -----------------------------------------------------------------------------

background: #dcdcdc
foreground: #2f2f2f

# Normal colors
color0:  #b0b0b0
color1:  #a8474a
color2:  #2c9279
color3:  #7a6020
color4:  #365ca8
color5:  #824699
color6:  #2c9279
color7:  #555555

# Bright colors
color8:  #bcbcbc
color9:  #cf3d43
color10: #00a284
color11: #8c6b00
color12: #1767d3
color13: #a13cc2
color14: #00a284
color15: #2f2f2f

# Extended colors
color16: #a04e1e
color17: #8c2d30
